export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";